name: marc_klesiewicz
description: A new Flutter template project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_route: ^7.1.0
  flutter_translate: ^4.0.2
  package_info_plus: ^4.0.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.0.3

  # TODO: Project dependent remove if not needed
  # Auth
  flutter_secure_storage: ^8.0.0 # Required android manifest minSdkVersion of 18 (Can be 16 if removed)
  synchronized: ^3.1.0

  # TODO: Keep if image picking is needed
  image_picker: ^0.8.7+5
  permission_handler: ^10.0.0

  # Misc
  auto_size_text: ^3.0.0
  firebase_crashlytics: ^3.3.1
  firebase_core: ^2.13.0
  universal_platform: ^1.0.0+1
  dio: ^5.0.0
  flutter_svg: ^2.0.7
  responsive_builder: ^0.7.0
  dyn_mouse_scroll: ^1.0.7
  rive: ^0.7.16
  rive_common: ^0.1.0
  url_launcher: ^6.1.12
  dropdown_button3: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.0.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  freezed: ^2.3.4
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  json_serializable: ^6.7.0
  build_runner: ^2.4.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/svgs/
    - assets/fonts/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
          weight: 400
        - asset: assets/fonts/EBGaramond-Medium.ttf
          weight: 500
        - asset: assets/fonts/EBGaramond-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: assets/fonts/EBGaramond-ExtraBold.ttf
          weight: 800
    - family: BerkshireSwash
      fonts:
        - asset: assets/fonts/BerkshireSwash-Regular.ttf
          weight: 400
